language: ruby

rvm:
  - 2.3.1
  - 2.3.0
  - 2.2.2
  - 2.1
  - 2.0.0
  - rbx-2

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile

sudo: false

bundler_args: '--without local_development --jobs 3 --retry 3'

script: bundle exec rake

matrix:
  fast_finish: true
  allow_failures:
      - gemfile: gemfiles/activerecord_edge.gemfile
      - rvm: rbx-2
  exclude:
      - rvm: 2.0.0
        gemfile: gemfiles/activerecord_4.2.gemfile
      - rvm: 2.2.2
        gemfile: gemfiles/activerecord_3.2.gemfile
      - rvm: rbx-2
        gemfile: gemfiles/activerecord_3.2.gemfile
      - rvm: 2.1
        gemfile: gemfiles/activerecord_5.0.gemfile
      - rvm: 2.0.0
        gemfile: gemfiles/activerecord_5.0.gemfile
      - rvm: rbx-2
        gemfile: gemfiles/activerecord_5.0.gemfile
